# Generated by Django 5.2.6 on 2025-10-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuffingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('part_code', models.CharField(max_length=50)),
                ('part_description', models.CharField(blank=True, max_length=200, null=True)),
                ('lot_qty', models.IntegerField()),
                ('ok_qty', models.IntegerField()),
                ('ng_qty', models.IntegerField()),
                ('reason_for_ng', models.TextField(blank=True, null=True)),
                ('operator', models.CharField(max_length=100)),
                ('incharge', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaskingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('item_description', models.CharField(max_length=200)),
                ('lot_qty', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('ok_qty_after_masking', models.IntegerField()),
                ('reject_qty', models.IntegerField()),
                ('defect', models.TextField(blank=True, null=True)),
                ('judgement', models.CharField(max_length=10)),
                ('prepared_by', models.CharField(max_length=100,blank=True, null=True)),
                ('verify_by', models.CharField(max_length=100,blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PainterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painter_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('part_no', models.CharField(max_length=100)),
                ('grn_no', models.CharField(max_length=100)),
                ('lot_qty', models.IntegerField(blank=True, null=True)),
                ('total_ok', models.IntegerField(blank=True, null=True)),
                ('moulding_chemical', models.IntegerField(blank=True, null=True)),
                ('rep_dust', models.IntegerField(blank=True, null=True)),
                ('rep_scratch', models.IntegerField(blank=True, null=True)),
                ('rep_less_paint', models.IntegerField(blank=True, null=True)),
                ('rep_colour_fin', models.IntegerField(blank=True, null=True)),
                ('rep_light_pass', models.IntegerField(blank=True, null=True)),
                ('rep_ok_qty', models.IntegerField(blank=True, null=True)),
                ('rework_person', models.CharField(blank=True, max_length=100, null=True)),
                ('painter_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('rej_dust', models.IntegerField(blank=True, null=True)),
                ('rej_scratch', models.IntegerField(blank=True, null=True)),
                ('rej_dent', models.IntegerField(blank=True, null=True)),
                ('rej_less_paint', models.IntegerField(blank=True, null=True)),
                ('rej_cut_mark', models.IntegerField(blank=True, null=True)),
                ('rej_paint_flow', models.IntegerField(blank=True, null=True)),
                ('qc_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('judgement', models.CharField(blank=True, max_length=10, null=True)),
                ('line_leader', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaintStirringEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('paint_name', models.CharField(max_length=100)),
                ('paint_code', models.CharField(max_length=100)),
                ('batch_code', models.CharField(max_length=100)),
                ('pkg_size', models.CharField(max_length=50)),
                ('pkg_references', models.CharField(max_length=100)),
                ('expry_date', models.DateField()),
                ('air_pressure', models.FloatField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('done_by', models.CharField(max_length=100)),
                ('judgement', models.CharField(max_length=10)),
                ('verify_by', models.CharField(max_length=100, blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
