# Generated by Django 5.2.6 on 2025-09-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PainterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painter_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('part_no', models.CharField(max_length=100)),
                ('grn_no', models.CharField(max_length=100)),
                ('lot_qty', models.IntegerField(blank=True, null=True)),
                ('total_ok', models.IntegerField(blank=True, null=True)),
                ('moulding_chemical', models.IntegerField(blank=True, null=True)),
                ('rep_dust', models.IntegerField(blank=True, null=True)),
                ('rep_scratch', models.IntegerField(blank=True, null=True)),
                ('rep_less_paint', models.IntegerField(blank=True, null=True)),
                ('rep_colour_fin', models.IntegerField(blank=True, null=True)),
                ('rep_light_pass', models.IntegerField(blank=True, null=True)),
                ('rep_ok_qty', models.IntegerField(blank=True, null=True)),
                ('rework_person', models.CharField(blank=True, max_length=100, null=True)),
                ('painter_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('rej_dust', models.IntegerField(blank=True, null=True)),
                ('rej_scratch', models.IntegerField(blank=True, null=True)),
                ('rej_dent', models.IntegerField(blank=True, null=True)),
                ('rej_less_paint', models.IntegerField(blank=True, null=True)),
                ('rej_cut_mark', models.IntegerField(blank=True, null=True)),
                ('rej_paint_flow', models.IntegerField(blank=True, null=True)),
                ('qc_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('judgement', models.CharField(blank=True, max_length=10, null=True)),
                ('line_leader', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
