# Generated by Django 5.2.6 on 2025-09-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuffingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('part_code', models.CharField(max_length=50)),
                ('part_description', models.CharField(blank=True, max_length=200, null=True)),
                ('lot_qty', models.IntegerField()),
                ('ok_qty', models.IntegerField()),
                ('ng_qty', models.IntegerField()),
                ('reason_for_ng', models.TextField(blank=True, null=True)),
                ('operator', models.CharField(max_length=100)),
                ('incharge', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]