# Generated by Django 5.2.6 on 2025-09-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0002_buffingentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_description', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('ok_qty_after_masking', models.IntegerField()),
                ('reject_qty', models.IntegerField()),
                ('defect', models.TextField(blank=True, null=True)),
                ('judgement', models.CharField(max_length=10)),
                ('prepared_by', models.CharField(max_length=100)),
                ('verify_by', models.CharField(max_length=100)),
            ],
        ),
    ]
