# Generated by Django 5.2.6 on 2025-09-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0003_maskingentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintStirringEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('paint_name', models.CharField(max_length=100)),
                ('paint_code', models.CharField(max_length=100)),
                ('batch_code', models.CharField(max_length=100)),
                ('pkg_size', models.CharField(max_length=50)),
                ('pkg_references', models.CharField(max_length=100)),
                ('expry_date', models.DateField()),
                ('air_pressure', models.FloatField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('done_by', models.CharField(max_length=100)),
                ('judgement', models.CharField(max_length=10)),
                ('verify_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
